# Generated by Django 5.2.8 on 2025-11-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('normalized', models.TextField()),
                ('updated_at', models.DateTimeField()),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'activities_catalog',
                'ordering': ['description'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeoDepartment',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('normalized', models.TextField()),
                ('updated_at', models.DateTimeField()),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'geo_departments',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeoMunicipality',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_code', models.CharField(max_length=4)),
                ('muni_code', models.CharField(max_length=4)),
                ('name', models.TextField()),
                ('normalized', models.TextField()),
                ('updated_at', models.DateTimeField()),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'geo_municipalities',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='activity_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='department_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='municipality_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
