# Generated by Django 5.2.8 on 2025-12-01 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_activity_geodepartment_geomunicipality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTERecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dte_type', models.CharField(max_length=20)),
                ('status', models.CharField(default='PENDIENTE', max_length=20)),
                ('control_number', models.CharField(blank=True, default='', max_length=100)),
                ('hacienda_uuid', models.CharField(blank=True, default='', max_length=100)),
                ('hacienda_state', models.CharField(blank=True, default='', max_length=50)),
                ('issuer_nit', models.CharField(blank=True, default='', max_length=32)),
                ('receiver_nit', models.CharField(blank=True, default='', max_length=32)),
                ('receiver_name', models.CharField(blank=True, default='', max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dte_records', to='api.invoice')),
            ],
            options={
                'db_table': 'api_dte_record',
                'indexes': [models.Index(fields=['dte_type'], name='api_dte_rec_dte_typ_e4783c_idx'), models.Index(fields=['status'], name='api_dte_rec_status_e7cc67_idx'), models.Index(fields=['control_number'], name='api_dte_rec_control_9359d9_idx'), models.Index(fields=['hacienda_uuid'], name='api_dte_rec_haciend_6cb1d6_idx'), models.Index(fields=['issue_date'], name='api_dte_rec_issue_d_92d962_idx'), models.Index(fields=['receiver_nit'], name='api_dte_rec_receive_597495_idx')],
            },
        ),
    ]
