# Generated by Django 5.2.8 on 2025-12-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dterecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='observations',
            field=models.TextField(blank=True, default=''),
        ),
    ]
