# Generated by Django 5.2.8 on 2025-12-06 20:41

from django.db import migrations, models
import django.db.models.deletion


def populate_staffuser_username(apps, schema_editor):
    StaffUser = apps.get_model("api", "StaffUser")
    for staff_user in StaffUser.objects.all():
        email = getattr(staff_user, "email", "") or ""
        if not staff_user.username:
            candidate = email.strip() or f"user-{staff_user.pk}"
            staff_user.username = candidate
        staff_user.save(update_fields=["username"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_client_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="nrc",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="client",
            name="direccion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="client",
            name="activity_description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="invoice",
            name="observations",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="DTERecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dte_type", models.CharField(max_length=20)),
                ("status", models.CharField(default="PENDIENTE", max_length=20)),
                ("control_number", models.CharField(blank=True, default="", max_length=100)),
                ("hacienda_uuid", models.CharField(blank=True, default="", max_length=100)),
                ("hacienda_state", models.CharField(blank=True, default="", max_length=50)),
                ("issuer_nit", models.CharField(blank=True, default="", max_length=32)),
                ("receiver_nit", models.CharField(blank=True, default="", max_length=32)),
                ("receiver_name", models.CharField(blank=True, default="", max_length=255)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("request_payload", models.JSONField()),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dte_records",
                        to="api.invoice",
                    ),
                ),
            ],
            options={
                "db_table": "api_dte_record",
            },
        ),
        migrations.AddIndex(
            model_name="dterecord",
            index=models.Index(fields=["dte_type"], name="api_dte_rec_dte_typ_e4783c_idx"),
        ),
        migrations.AddIndex(
            model_name="dterecord",
            index=models.Index(fields=["status"], name="api_dte_rec_status_e7cc67_idx"),
        ),
        migrations.AddIndex(
            model_name="dterecord",
            index=models.Index(fields=["control_number"], name="api_dte_rec_control_9359d9_idx"),
        ),
        migrations.AddIndex(
            model_name="dterecord",
            index=models.Index(fields=["hacienda_uuid"], name="api_dte_rec_haciend_6cb1d6_idx"),
        ),
        migrations.AddIndex(
            model_name="dterecord",
            index=models.Index(fields=["issue_date"], name="api_dte_rec_issue_d_92d962_idx"),
        ),
        migrations.AddIndex(
            model_name="dterecord",
            index=models.Index(fields=["receiver_nit"], name="api_dte_rec_receive_597495_idx"),
        ),
        migrations.RenameField(
            model_name="staffuser",
            old_name="name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="staffuser",
            old_name="active",
            new_name="is_active",
        ),
        migrations.AlterField(
            model_name="staffuser",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="staffuser",
            name="username",
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="staffuser",
            name="password",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.RunPython(populate_staffuser_username, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="staffuser",
            name="email",
        ),
        migrations.AlterField(
            model_name="staffuser",
            name="role",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="staffuser",
            name="password",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="staffuser",
            name="username",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterModelTable(
            name="staffuser",
            table="api_staffuser",
        ),
    ]
