# Generated by Django 5.2.8 on 2025-12-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_invoice_observations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffuser',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffuser',
            name='name',
        ),
        migrations.AddField(
            model_name='staffuser',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='password',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffuser',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterModelTable(
            name='staffuser',
            table='api_staffuser',
        ),
    ]
