# Generated by Django 5.2.8 on 2025-12-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_active_staffuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activity_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='direccion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='client',
            name='nrc',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
