# Generated by Django 5.2.8 on 2025-12-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_client_is_deleted'),
        ('api', '0006_client_activity_description_client_direccion_and_more'),
    ]

    operations = [
    ]
