# Generated by Django 5.2.8 on 2025-12-07 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_invoice_dte_fields'),
        ('api', '0007_merge_20251202_1123'),
    ]

    operations = [
    ]
