# Generated by Django 5.2.8 on 2025-12-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_invoice_credit_note_fields'),
        ('api', '0008_merge_20251206_2041'),
    ]

    operations = [
    ]
