# Generated by Django 5.2.8 on 2026-01-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_invoice_has_credit_note_default'),
        ('api', '0009_merge_20251207_0020'),
    ]

    operations = [
    ]
