# Generated by Django 5.2.8 on 2026-01-06 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dte_control_counter'),
        ('api', '0010_merge_20260105_1343'),
    ]

    operations = [
    ]
