# Generated by Django 5.2.8 on 2026-01-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_invoice_item_price_override_fields'),
        ('api', '0011_merge_20260106_1504'),
    ]

    operations = [
    ]
