# Generated by Django 5.2.8 on 2026-01-13 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_invoice_dte_send_fields'),
        ('api', '0012_merge_20260106_1732'),
    ]

    operations = [
    ]
