# Generated by Django 5.2.8 on 2026-01-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_invoice_dte_tracking_fields'),
        ('api', '0013_merge_20260113_0119'),
    ]

    operations = [
    ]
