# Generated by Django 6.0.1 on 2026-01-15 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_normalize_invoice_dte_statuses"),
    ]

    operations = [
        migrations.CreateModel(
            name="DTEInvalidation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ENVIANDO", "ENVIANDO"),
                            ("PENDIENTE", "PENDIENTE"),
                            ("ACEPTADO", "ACEPTADO"),
                            ("RECHAZADO", "RECHAZADO"),
                        ],
                        default="ENVIANDO",
                        max_length=20,
                    ),
                ),
                (
                    "codigo_generacion",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("tipo_anulacion", models.IntegerField(default=1)),
                ("motivo_anulacion", models.TextField(blank=True, default="")),
                (
                    "original_codigo_generacion",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "original_numero_control",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "original_sello_recibido",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "original_tipo_dte",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "original_fec_emi",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "original_monto_iva",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("request_payload", models.JSONField(default=dict)),
                ("response_payload", models.JSONField(blank=True, null=True)),
                (
                    "hacienda_state",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=50, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dte_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invalidations",
                        to="api.dterecord",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dte_invalidations",
                        to="api.invoice",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.staffuser",
                    ),
                ),
            ],
            options={
                "db_table": "api_dte_invalidation",
                "indexes": [
                    models.Index(
                        fields=["status"], name="api_dte_inv_status_2c3ad9_idx"
                    ),
                    models.Index(
                        fields=["codigo_generacion"],
                        name="api_dte_inv_codigo__9a4df6_idx",
                    ),
                    models.Index(
                        fields=["original_numero_control"],
                        name="api_dte_inv_origina_10ca1f_idx",
                    ),
                ],
            },
        ),
    ]
